# Generated by Django 5.2.7 on 2025-10-23 16:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("solicitudes", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Area",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100, unique=True)),
                ("descripcion", models.TextField(blank=True)),
                ("activo", models.BooleanField(default=True)),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name_plural": "Áreas",
                "ordering": ["nombre"],
            },
        ),
        migrations.AlterModelOptions(
            name="programa",
            options={
                "ordering": ["area", "nombre"],
                "verbose_name_plural": "Programas",
            },
        ),
        migrations.AddField(
            model_name="programa",
            name="activo",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="programa",
            name="duracion_horas",
            field=models.IntegerField(
                blank=True, help_text="Duración en horas", null=True
            ),
        ),
        migrations.AddField(
            model_name="programa",
            name="fecha_creacion",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name="instructor",
            name="especialidad",
            field=models.ManyToManyField(
                related_name="instructores", to="solicitudes.programa"
            ),
        ),
        migrations.AlterField(
            model_name="programa",
            name="nombre",
            field=models.CharField(max_length=200),
        ),
        migrations.AddField(
            model_name="programa",
            name="area",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="programas",
                to="solicitudes.area",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="programa",
            unique_together={("area", "nombre")},
        ),
    ]
