# Generated by Django 5.2.7 on 2026-02-16 12:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Reporte",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("solicitudes", "Solicitudes de Formación"),
                            ("empresas", "Directorio de Empresas"),
                            ("programas", "Catálogo de Programas"),
                            ("instructores", "Directorio de Instructores"),
                            ("consolidado", "Reporte Consolidado"),
                        ],
                        db_index=True,
                        max_length=20,
                        verbose_name="Tipo de Reporte",
                    ),
                ),
                (
                    "formato",
                    models.CharField(
                        choices=[("pdf", "PDF"), ("excel", "Excel")],
                        max_length=10,
                        verbose_name="Formato",
                    ),
                ),
                (
                    "fecha_generacion",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        verbose_name="Fecha de Generación",
                    ),
                ),
                (
                    "filtros_aplicados",
                    models.JSONField(
                        blank=True,
                        help_text="Filtros usados en la generación del reporte",
                        null=True,
                        verbose_name="Filtros Aplicados",
                    ),
                ),
                (
                    "total_registros",
                    models.IntegerField(
                        default=0,
                        help_text="Cantidad de registros incluidos en el reporte",
                        verbose_name="Total de Registros",
                    ),
                ),
                (
                    "tiempo_generacion",
                    models.FloatField(
                        default=0,
                        help_text="Tiempo que tomó generar el reporte en segundos",
                        verbose_name="Tiempo de Generación (seg)",
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True,
                        help_text="IP desde donde se generó el reporte",
                        null=True,
                        verbose_name="Dirección IP",
                    ),
                ),
                (
                    "generado_por",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reportes_generados",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Generado por",
                    ),
                ),
            ],
            options={
                "verbose_name": "Reporte",
                "verbose_name_plural": "Reportes",
                "ordering": ["-fecha_generacion"],
                "indexes": [
                    models.Index(
                        fields=["-fecha_generacion"],
                        name="reportes_re_fecha_g_36349e_idx",
                    ),
                    models.Index(
                        fields=["generado_por", "-fecha_generacion"],
                        name="reportes_re_generad_59865d_idx",
                    ),
                    models.Index(
                        fields=["tipo", "-fecha_generacion"],
                        name="reportes_re_tipo_09d459_idx",
                    ),
                ],
            },
        ),
    ]
