# Generated by Django 5.2.7 on 2026-04-08 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("instructores", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="instructor",
            name="cedula",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="Cédula"
            ),
        ),
    ]
