# Generated by Django 5.2.7 on 2026-04-08 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("instructores", "0002_instructor_cedula"),
    ]

    operations = [
        migrations.AlterField(
            model_name="instructor",
            name="cedula",
            field=models.CharField(max_length=10, unique=True, verbose_name="Cédula"),
        ),
    ]
