# Generated by Django 5.2.7 on 2025-10-23 19:56

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("empresas", "0001_initial"),
        ("instructores", "0001_initial"),
        ("programas", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Solicitud",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "fecha_recepcion",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("fecha_respuesta", models.DateTimeField(blank=True, null=True)),
                ("fecha_atencion", models.DateTimeField(blank=True, null=True)),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("RECIBIDA", "Recibida"),
                            ("RESPONDIDA", "Respondida"),
                            ("ATENDIDA", "Atendida"),
                            ("FINALIZADA", "Finalizada"),
                        ],
                        default="RECIBIDA",
                        max_length=20,
                    ),
                ),
                ("observaciones", models.TextField(blank=True)),
                (
                    "empresa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="empresas.empresa",
                    ),
                ),
                (
                    "instructor_asignado",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="instructores.instructor",
                    ),
                ),
                (
                    "programa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="programas.programa",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Solicitudes",
                "ordering": ["-fecha_recepcion"],
            },
        ),
    ]
