# Generated by Django 5.2.7 on 2025-10-23 13:47

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Empresa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=200)),
                ("contacto", models.CharField(max_length=100)),
                ("telefono", models.CharField(max_length=20)),
                ("correo", models.EmailField(max_length=254)),
                ("numero_trabajadores", models.IntegerField()),
                ("municipio", models.CharField(max_length=100)),
                ("fecha_registro", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name_plural": "Empresas",
            },
        ),
        migrations.CreateModel(
            name="Programa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        choices=[
                            ("RETROCARGADOR", "Operador de Retrocargador"),
                            ("EXCAVADORA", "Operador de Excavadora"),
                            ("EXPLOTACION", "Explotacion de Obras Civiles y Mineras"),
                            ("MINICARGADOR", "Minicargador"),
                            ("MONTACARGAS", "Montacargas"),
                            (
                                "SISTEMA_HID",
                                "Sistemas Hidraulicos en Maquinaria Pesada",
                            ),
                        ],
                        max_length=100,
                    ),
                ),
                ("descripcion", models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name="Instructor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                ("telefono", models.CharField(max_length=20)),
                ("correo", models.EmailField(max_length=254)),
                ("activo", models.BooleanField(default=True)),
                ("especialidad", models.ManyToManyField(to="solicitudes.programa")),
            ],
            options={
                "verbose_name_plural": "Instructores",
            },
        ),
        migrations.CreateModel(
            name="Solicitud",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "fecha_recepcion",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("fecha_respuesta", models.DateTimeField(blank=True, null=True)),
                ("fecha_atencion", models.DateTimeField(blank=True, null=True)),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("RECIBIDA", "Recibida"),
                            ("RESPONDIDA", "Respondida"),
                            ("ATENDIDA", "Atendida"),
                            ("FINALIZADA", "Finalizada"),
                        ],
                        default="RECIBIDA",
                        max_length=20,
                    ),
                ),
                ("observaciones", models.TextField(blank=True)),
                (
                    "empresa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="solicitudes.empresa",
                    ),
                ),
                (
                    "instructor_asignado",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="solicitudes.instructor",
                    ),
                ),
                (
                    "programa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="solicitudes.programa",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Solicitudes",
                "ordering": ["-fecha_recepcion"],
            },
        ),
    ]
