# Generated by Django 5.2.7 on 2025-12-17 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("solicitudes", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="solicitud",
            name="fecha_finalizacion",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="solicitud",
            name="numero_aprendices",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
