# Generated by Django 5.2.7 on 2025-12-24 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("solicitudes", "0002_solicitud_fecha_finalizacion_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="solicitud",
            name="correo_remitente",
            field=models.EmailField(
                blank=True,
                help_text="Email desde donde se envió la solicitud original",
                max_length=255,
                null=True,
                verbose_name="Correo del Remitente",
            ),
        ),
    ]
