# Generated by Django 5.2.7 on 2026-01-06 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("solicitudes", "0003_solicitud_correo_remitente"),
    ]

    operations = [
        migrations.AddField(
            model_name="solicitud",
            name="documento_pdf",
            field=models.FileField(
                blank=True,
                help_text="Documento adjunto de la solicitud (solo PDF)",
                null=True,
                upload_to="solicitudes/documentos/%Y/%m/",
                verbose_name="Documento PDF",
            ),
        ),
    ]
