# Generated by Django 5.2.7 on 2026-01-15 14:37

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("solicitudes", "0004_solicitud_documento_pdf"),
    ]

    operations = [
        migrations.CreateModel(
            name="DocumentoSolicitud",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "archivo",
                    models.FileField(
                        upload_to="solicitudes/documentos/%Y/%m/",
                        verbose_name="Archivo PDF",
                    ),
                ),
                (
                    "nombre_archivo",
                    models.CharField(max_length=255, verbose_name="Nombre del archivo"),
                ),
                (
                    "fecha_subida",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name="Fecha de subida",
                    ),
                ),
                (
                    "solicitud",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documentos",
                        to="solicitudes.solicitud",
                    ),
                ),
            ],
            options={
                "verbose_name": "Documento de Solicitud",
                "verbose_name_plural": "Documentos de Solicitudes",
                "ordering": ["-fecha_subida"],
            },
        ),
    ]
