# Generated by Django 5.2.7 on 2026-03-27 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("solicitudes", "0005_documentosolicitud"),
    ]

    operations = [
        migrations.AlterField(
            model_name="solicitud",
            name="estado",
            field=models.CharField(
                choices=[
                    ("RECIBIDA", "Recibida"),
                    ("ATENDIDA", "Atendida"),
                    ("RESPONDIDA", "Respondida"),
                    ("FINALIZADA", "Finalizada"),
                ],
                default="RECIBIDA",
                max_length=20,
            ),
        ),
    ]
