# Generated by Django 5.2.7 on 2026-04-08 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("solicitudes", "0006_alter_solicitud_estado"),
    ]

    operations = [
        migrations.AddField(
            model_name="solicitud",
            name="fecha_fin_formacion",
            field=models.DateField(
                blank=True,
                help_text="Fecha en que el instructor termina de dictar la formación. Al cumplirse, la solicitud se finaliza automáticamente.",
                null=True,
                verbose_name="Fecha fin de formación",
            ),
        ),
    ]
