# Generated by Django 5.2.7 on 2025-10-23 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Empresa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=200)),
                ("contacto", models.CharField(max_length=100)),
                ("telefono", models.CharField(max_length=20)),
                ("correo", models.EmailField(max_length=254)),
                ("numero_trabajadores", models.IntegerField()),
                ("municipio", models.CharField(max_length=100)),
                ("fecha_registro", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name_plural": "Empresas",
            },
        ),
    ]
