# Generated by Django 5.2.7 on 2025-11-18 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("empresas", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="empresa",
            name="direccion",
            field=models.CharField(blank=True, default="", max_length=250),
        ),
    ]
