# Generated by Django 5.2.7 on 2025-11-20 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("empresas", "0002_empresa_direccion"),
    ]

    operations = [
        migrations.AddField(
            model_name="empresa",
            name="activo",
            field=models.BooleanField(default=True, verbose_name="Activo"),
        ),
    ]
