# Generated by Django 5.2.7 on 2025-12-04 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("empresas", "0003_empresa_activo"),
    ]

    operations = [
        migrations.AddField(
            model_name="empresa",
            name="nit",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="NIT"
            ),
        ),
    ]
