# Generated by Django 5.2.7 on 2025-12-23 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("empresas", "0004_empresa_nit"),
    ]

    operations = [
        migrations.AlterField(
            model_name="empresa",
            name="nit",
            field=models.CharField(
                blank=True,
                help_text="Número de Identificación Tributaria (único)",
                max_length=20,
                null=True,
                unique=True,
                verbose_name="NIT",
            ),
        ),
    ]
