# Generated by Django 5.2.7 on 2025-10-23 19:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("area_formacion", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Programa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=200)),
                ("descripcion", models.TextField(blank=True)),
                (
                    "duracion_horas",
                    models.IntegerField(
                        blank=True, help_text="Duración en horas", null=True
                    ),
                ),
                ("activo", models.BooleanField(default=True)),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                (
                    "area",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="programas",
                        to="area_formacion.area",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Programas",
                "ordering": ["area", "nombre"],
                "unique_together": {("area", "nombre")},
            },
        ),
    ]
