# Generated by Django 5.2.7 on 2025-11-24 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("programas", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="programa",
            name="codigo",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Código interno del programa",
                max_length=50,
            ),
        ),
    ]
